### ISSUE TITLE
pg-transaction does not maintain pg settings

### ISSUE THREAD

**Issue by agad** [goodybag/node-pg-transaction#1]
I set the typeparsers for bigints in pg because bigints do not translate correctly from PG.  I do this via:

pg.types.setTypeParser(20, String);

However,  pg-transaction redefines pg for the client.  And then uses it in the query thus overwriting the pg.types setting executed outside of the transaction.

**Comment by lalitkapoor** [comment]
@agad Can you provide an example that fails? Thanks.

**Comment by agad** [comment]
You can use this test from pg: https://github.com/brianc/node-postgres/blob/master/test/integration/client/huge-numeric-tests.js#L6

To get a quick hack, I changed the transaction constructor:

var Transaction = module.exports = function(client, pgClient) {
  this.client = client;
  this.pgClient = pgClient || require('pg').Client;
};

and then changed the line in the query method that referred to pgClient.  Not sure that's how you want to deal with it on a larger scale, but it worked like a charm for me.

**Comment by agad** [comment]
You can also see https://github.com/brianc/node-postgres/issues/107 and https://github.com/brianc/node-postgres/issues/166 for a discussion about this issue.

**Comment by lalitkapoor** [comment]
@agad in the test case I just added it seems to function correctly. I added

``` javascript
pg.types.setTypeParser(20, String);
```

I then insert a row and query for that row. The result is of the type string for that specific column.

Can you modify the test case such that it fails for your use case? or provide me with a failing example?

**Comment by lalitkapoor** [comment]
@agad you can checkout branch 1-pg-transaction-does-not-maintain-pg-settings if you'd like to run the test.

**Comment by agad** [comment]
Close it out.  I refreshed my install from NPM, and I am now receiving the correct values.  Not sure what happened.  Sorry for any extra work I caused you.
